###########################################################################
# Dugong, BioPortainer & BioBox
# ========================================================
#
# Current development is led by Fabiano Menegidio.
#
# Bioinformatician/Bioinformaticist at the Laboratory of Functional 
# and Structural Genomics of the Integrated Nucleus of Biotechnology 
# at the University of Mogi das Cruzes, Brazil.
# 
# Contact: fabiano.menegidio@biology.bio.br
# GitHub: https://github.com/fabianomenegidio
# GitHub: https://github.com/orgs/DugongBioinformatics
# GitHub: https://github.com/bioportainer
#
###########################################################################

FROM bioportainer/biogui:cpu

###########################################################################
# Environment config
###########################################################################

